version: '3.8'

services:
  web:
    build: .
    restart: always
    user: "1000:1000"  # استفاده از UID/GID هاست برای جلوگیری از مشکلات permission
    volumes:
      - .:/app
      - media_volume:/app/media  # ✅ mount media به داخل کانتینر
      - static_volume:/app/staticfiles
    depends_on:
      - db
    environment:
      - DEBUG=False
      - SECRET_KEY=django-insecure-ke0$uicco09-)3a&6!sjwlj890ws_fe&7k_aq-=vzibs_d=j-l
      - DATABASE_URL=postgresql://postgres:1111@db:5432/postgreserd_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network

  db:
    image: postgres:13
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=1111
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgreserd_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  nginx:
    image: nginx:1.21
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/app/staticfiles
      - media_volume:/media  # ✅ media mount به مسیر درست در nginx
    ports:
      - "80:80"
    depends_on:
      web:
        condition: service_healthy
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
